name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev  # تغییر libtinfo5 به libtinfo6
        sudo update-alternatives --config java
    
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip wheel setuptools
        pip install buildozer cython==0.29.36
    
    - name: Build APK with Buildozer
      run: |
        buildozer -v android release
        cp bin/*.apk .
    
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: english-quiz-app
        path: *.apk
        retention-days: 7
